### ISSUE TITLE
RFC6265 - cookies specification

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#10]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;

"[COOKIES]
Adam Barth. HTTP State Management Mechanism. April 2011. Internet Proposed Standard RFC 6265. URL: http://www.rfc-editor.org/rfc/rfc6265.txt"

**Comment by davemevans** [comment]
Duplicate of #9?

**Comment by mavgit** [comment]
RFC 6265 is referenced by both [HTML 5](https://www.w3.org/TR/html5/single-page.html#refsCOOKIES) and [HTML 5.1](https://www.w3.org/TR/html51/single-page.html#biblio-cookies). Since the Web Media API spec will reference HTML 5 or HTML 5.1, it's not required for it to reference RFC 6265 directly.

If there's something specific we need to reference in RFC 6265 (e.g. Issue #9), we can always add it as part of that change.

So, I'd recommend closing this issue and continuing discussion in #9.

**Comment by jpiesing** [comment]
@mavgit OK.
