### ISSUE TITLE
CSS Text Module Level 3

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#11]
One of the references in the OIPF Web Standards TV Profile (http://www.oipf.tv/docs/OIPF-T1-R2-Specification-Volume5a-Web-Standards-TV-Profile-v2_3-2014-01-24.pdf ) (with HbbTV updates) that isn't in the November 28th 2016 version of the Web Media API (https://w3c.github.io/webmediaapi/#normative-references ) is the following;
[CSS3TEXT-20121113]
Elika J. Etemad; Koji Ishii. CSS Text Module Level 3. 13 November 2012. W3C Working Draft. URL: http://www.w3.org/TR/2012/WD-css3-text-20121113/

**Comment by mavgit** [comment]
i note that CSS Text Module Level 3 is included as a [Normative Reference in HTML 5.1](https://www.w3.org/TR/html51/references.html#normative).

>[CSS-TEXT-3]
Elika Etemad; Koji Ishii. CSS Text Module Level 3. 10 October 2013. LCWD. URL: https://www.w3.org/TR/css-text-3/

So, I don't think we need to add a reference to CSS-TEXT-3 to the Web Media API spec, assuming we continue to reference HTML 5.1.

**Comment by tidoust** [comment]
Same comment as in #16: CSS-TEXT-3 is normatively referenced by HTML5.1 but only for specific uses related to `<center>`, `<pre>` and the `align` attribute, so we may still want to be explicit about support here.

CSS-TEXT-3 replaces and extends section 16 of CSS 2.1. I do not know to which extent we need to require the CSS-TEXT-3 specification. I see that the OIPF spec calls for support for `text-shadow`, which has since then been moved to [CSS Text Decoration Module Level 3](http://www.w3.org/TR/css-text-decor-3/).

The CSS Snapshot 2015 notes that this module is among the list of modules that "have completed design work, and are fairly stable, but have not received much testing and implementation experience yet".

**Comment by davemevans** [comment]
Given that the only OIPF-mandated feature is no longer part of this module, some basic use cases are covered in HTML5.1, and implementation is unclear, shall we close this ticket with no action?

If `text-shadow` is still necessary, a new issue discussing CSS Text Decoration should be opened.

**Comment by davemevans** [comment]
**Call for consensus:** Close issue as discussed in https://github.com/w3c/webmediaapi/issues/11#issuecomment-283935052

**Comment by davemevans** [comment]
Consensus reached on telco 8/3/2017.
