### ISSUE TITLE
Respec warning caused by processVersion

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#134]
For some reason, we set a ReSpec option called `processVersion` which tells ReSpec to report the specific version of the W3C process under which the document was developed.

This isn't necessary (ReSpec just uses the latest if it isn't specified [1]), assuming we always want to develop the document under the latest process, causes a warning when ReSpec renders the page, and creates a maintenance hassle as we need to update the field each year (we've already dealt with this last year - https://github.com/w3c/webmediaapi/pull/76#issuecomment-311661884)

I propose we remove this field from the ReSpec config.

[1] https://github.com/w3c/respec/wiki/processVersion (note that the wiki page is out of date - ReSpec know it is now the 2018 Process).

**Comment by mavgit** [comment]
I agree with removing processVersion from our spec. The [ReSpec Editor's Guide for processVersion](https://github.com/w3c/respec/wiki/processVersion) has a comment that  "Generally, you want ReSpec to set this for you unless there is a good reason to use an old process"

FYI, processVersion is there because I started our spec by copying the sample spec template on the [ReSpec Editor's Guide](https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide), which includes processVersion. The Guide states:

> That is essentially the smallest W3C specification you can write using ReSpec (in practice, you could eliminate a few things but then you would have a truly useless document). Some of the configuration may seem cryptic, but it is there because all W3C documents must have some specific information available

which led me to believe that processVersion should be kept in any spec.

@tidoust In addition to removing processVersion from our spec, it would seem to indicate that processVersion should also be eliminated from the ReSpec Editor's Guide sample "smallest specification you can write"!

**Comment by tidoust** [comment]
> @tidoust In addition to removing processVersion from our spec, it would seem to indicate that processVersion should also be eliminated from the ReSpec Editor's Guide sample "smallest specification you can write"!

Indeed. Now removed from ReSpec Editor's Guide example.
