### ISSUE TITLE
Requirements on URL length

### ISSUE THREAD

**Issue by johnluther** [w3c-cg/webmediaapi#156]
Related to issue #144 (and also https://github.com/w3c/webmediaporting/issues/14 in the deprecated porting spec repo), I researched the URL length that each of the four major browser code bases supports. The goal is to state a min-max guidance range in the Web Media API spec.

I couldn't find any documented ranges from the browser vendors themselves, but in reading some discussion forums, I found:

```
Browser     Address bar   document.location  
                            or anchor tag
------------------------------------------
Chrome          32779           >64k
Firefox          >64k           >64k
Safari           >64k           >64k
Edge             2047          10240
```

Given that Edge has an address bar limit of 2047 characters, it seems that using 2047 as the maximum of the range would be the safest approach.

**Comment by mavgit** [comment]
I'm not sure the address bar is a relevant limit, since it's not a likely UI for smart TVs and other consumer products. I think we're better testing against the limit of URLs that can be supported on network operations, such as from apps and from HTTP headers. So, the second column seems more relevant, though the numbers seem crazy high!

It would be great to get some verification of these numbers from some browser vendors.

Also, in [my comment at the meeting](
https://github.com/w3c/webmediaapi/issues/144#issuecomment-432683779), I suggested we gather data from the four browsers above _plus_ the two main mobile browsers (iOS Safari and Android Chrome). Given their smaller resources than PCs, I would guess that the mobile browsers would give us lower numbers more appropriate for PCs.

**Comment by johnluther** [comment]
In the research I did, the lengths were the same across all platforms, including mobile. I will try to find more documentation on that.

I will also ping some people at Google, Apple and Mozilla. It was surprising to me how little "official" documentation there was from the vendors on this.

**Comment by mavgit** [comment]
In the 2018-10-25 HATF call, there was consensus to include the URL requirements and to delete the copy/paste error SessionStorage requirement.

**Comment by mavgit** [comment]
Fixed URL requirement. Closing.
