### ISSUE TITLE
Four code bases?

### ISSUE THREAD

**Issue by chrisn** [w3c-cg/webmediaapi#316]
This was previously discussed in https://github.com/w3c/webmediaapi/issues/200 (in 2019), but should the Web Media API Snapshot now describe three rather than "four of the most widely used user agent code bases"?

I also notice the snapshot doesn't mention these by name. Although it may be obvious to us I think it's worth spelling out more clearly which codebases it's referring to.

**Comment by JohnRiv** [comment]
Thanks for raising this @chrisn. A few observations to help guide the discussion:

1. The Browser Specific Failures graph at the top of https://wpt.fyi/ lists only Chrome, Firefox and Safari
2. The test results of the most recent runs for Chrome and Edge on https://wpt.fyi show 1787162 passing tests on Chrome vs. 1781612 for Edge (a difference of 5,550 more for Chrome)
3. https://wpt.fyi/interop-2023 combines Chrome & Edge into a single column

Also regarding mentioning the user agents by name, if we include their names, we'll have to decide among these 3 options for how to refer to them:
1. Chrome/Edge, Firefox, Safari
2. Chrome, Firefox, Safari
3. Chromium, Gecko, WebKit

**Comment by chrisn** [comment]
When deciding on features to include in the Web Media API Snapshot, do you make a distinction between features in Chrome that may not be in Edge, and vice versa? That could be an argument for sticking with four rather than three.

If we're actually basing decisions on the browsers in popular use, more than the underlying engine, then I think either option 1 or 2 is preferable.

**Comment by JohnRiv** [comment]
Based on what I'm seeing with the announcements around Baseline, listing all 4 browsers seems to make the most sense, as that is done at both MDN's main page (https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility) and Google's web.dev page (https://web.dev/baseline/).

So if we go with changing to say "three" rather than "four", option 1 seems to be the way to go.

**Comment by chrisn** [comment]
I agree, given Baseline includes four, it makes sense to follow that here. I would still recommend naming them in the Snapshot, though. Should I create a PR?

**Comment by JohnRiv** [comment]
> I agree, given Baseline includes four, it makes sense to follow that here. I would still recommend naming them in the Snapshot, though. Should I create a PR?

Sounds good. A PR at your convenience would be great, thanks.

**Comment by tidoust** [comment]
MDN visually lists Chrome and Edge together in the Baseline banner, so that's more 3.5 browsers than 4 in practice ;)

For what it's worth, it may be premature to look at Baseline as a source of truth. The notion of Baseline is still somewhat in flux and there are only 4 features flagged as part of Baseline on MDN for now (plus two flagged as "not Baseline"). Baseline is under discussion in the [WebDX Community Group](https://www.w3.org/community/webdx/). [Open issues](https://github.com/web-platform-dx/feature-set/issues) include considerations on the browsers (and versions) to look at.

Side note: since Baseline is meant to roughly capture features that are "safe to use" on the web, it will be useful to check that any feature that ends up being identified as Baseline is also in the Web Media API. The Web Media API may want to be more optimistic on other features, although it could be interesting to look at where and why a divergence may be needed.

**Comment by JohnRiv** [comment]
Closed via #317 at the August 16th HATF call
