### ISSUE TITLE
Use of 'support'

### ISSUE THREAD

**Issue by jeremypoulter** [w3c-cg/webmediaapi#51]
I think the use of 'support' can be ambiguous and highly subjective, eg "Devices must support the following specifications:
HTML 5.1 [HTML51]
...

What does it mean to support HTML 5.1? One could argue that if I have a device serving a HTML 5 document that supports HTML5. 

We should probably use language along the lines of; "Devices must implement rendering of all mandatory elements of  documents conformant to the following specifications;", "Devices must implement rendering of all mandatory elements of the following specifications;" or some combinations of the two.

**Comment by tidoust** [comment]
Note this is related to issue #21 (Specify conformance class when needed, for HTML5.1 in particular) where I propose to reuse the actual names used to describe conformance classes in HTML 5.1.

I did not react on the use of "support" in #21. If you feel it is ambiguous, I would suggest to:

1. Add a "Conformance" section that clarifies the use of RFC2119 terms among other things and defines the class of product that the Web Media API applies to (the subject of normative statements, in other words the term "Device", which could also be simply renamed to "User agent"). This is good practice in any case, see [A conformance clause is essential](http://www.w3.org/TR/qaframe-spec/#conformance-clause) in the Specification Guidelines. See, e.g. the [Presentation API](https://w3c.github.io/presentation-api/#conformance) for an example of a conformance clause.
2. Use "be conforming implementations of" instead of "support", as in "Devices must *be conforming implementations of* the following specifications". Or keep "support" and define how it is to be read in the conformance clause.

**Comment by thasso** [comment]
At the editors meeting we agreed to use the phrase "be conforming implementations of" instead of support and we will also add a Conformance to the document.

**Comment by davemevans** [comment]
**Call for consensus:** Close this is via #58, which implements the change in https://github.com/w3c/webmediaapi/issues/51#issuecomment-287096481.

**Comment by davemevans** [comment]
Consensus reached on 22/03/17 telco. Closed via e57dd9d.
