### ISSUE TITLE
objection to PR #62 as implemented after 05/04/17 call

### ISSUE THREAD

**Issue by jpiesing** [w3c-cg/webmediaapi#67]
PR #62 says;
"This was discussed and consensus reached on the 05/04/17 call."

I'm told the relevant part of the minutes from the 05/04/17 call are the following;

Mr. Vickers reviewed an editorial change in the spec to allow the document to remain a single document and not require a second document for APIs with exceptions. Agreed.

Unfortunately I don't believe part of the actual text that was included in the PR was agreed;

>     3. APIs not to be tested due to insufficient cross-platform support
>    When requiring conformance to a specification in Required Specifications, the CG recognizes that some features are not currently implemented across all web platforms and, consequently, the features listed below will not be tested as part of our tests.
>    Note that this is not an attempt to subset the web platform, or remove features from existing Web APIs, but merely noting exceptions to be made during the testing for conformance to this specification.

What is minuted is an agreed compromise between two points of view however unfortunately this text does not reflect one of the points of view.

**Comment by mavgit** [comment]
Proposed text from meeting: "The exceptions section includes APIs within required specs that are not supported across all four target code bases. This reflects the reality that not all APIs are implemented across all code bases."

**Comment by davemevans** [comment]
@jpiesing 
Are you happy with the text proposed in https://github.com/w3c/webmediaapi/issues/67#issuecomment-295311046? If not, please could you propose some alternative/additional text for the group to find consensus on?

Is the proposed text intended to completely replace the quoted text above? The proposal makes no mention of not subsetting the web platform, what an exception actually means etc.

**Comment by jpiesing** [comment]
Here is my proposal;

> 3. APIs not widely implemented across all web platforms
> When requiring conformance to a specification in Required Specifications, it must be recognised that parts of some web specifications are not currently implemented across all web platforms and may never be. Consequently, the features listed below may not be present in some implementations of this specification and will not be tested as part of our tests.
> Note that this is not an attempt to further subset the web platform beyond that resulting from some user agent developers deciding not to implement parts of a specification.
>3.1 General Exceptions
>3.1.1 At-risk features
>Some specifications referenced in Required Specifications may not have reached Recommendation and, as such, may contain 'at-risk' features. Since the most common reason for features being marked as at-risk is lack of implementations, such features may not be present in some implementations of this specification and will not be tested as part of our tests.

**Comment by mavgit** [comment]
Call for Consensus

>Note that this is not an attempt to further subset the web platform beyond that resulting from some user agent developers deciding not to implement parts of a specification.

My concern here is that this sentence can be read as stating the "some user agent developers" are subsetting the web platform when "deciding not to implement parts of a specification". I expect that some user agent developers may object to that characterization. I think we'd be better making no statement on the issue.

I Call for Consensus that we adopt Jon's proposed text with that one sentence deleted:

>3. APIs not widely implemented across all web platforms
When requiring conformance to a specification in Required Specifications, it must be recognised that parts of some web specifications are not currently implemented across all web platforms and may never be. Consequently, the features listed below may not be present in some implementations of this specification and will not be tested as part of our tests.
3.1 General Exceptions
3.1.1 At-risk features
Some specifications referenced in Required Specifications may not have reached Recommendation and, as such, may contain 'at-risk' features. Since the most common reason for features being marked as at-risk is lack of implementations, such features may not be present in some implementations of this specification and will not be tested as part of our tests.

**Comment by davemevans** [comment]
Consensus reached on 14/06/17 call.
