### ISSUE TITLE
Is "requiring" still appropriate now this is a snapshot?

### ISSUE THREAD

**Issue by davemevans** [w3c-cg/webmediaapi#93]
#88 changed the title of the document to snapshot, and #84 moved away from "requiring" towards documenting the current state of the web platform as a whole.

As a result, it seems to me that, adding a specification to Section 2 doesn't "require" it but merely documents it as being well supported, documented exceptions aside.

There are numerous mentions of the word "require" in the introduction and introductions to each section. Are these still appropriate?

**Comment by mavgit** [comment]
I spoke with Dave and cleared up a misunderstanding. While we are deriving the list of APIs via documenting API support on the web platform, we still need to require those APIs in order to support device manufacturers using this spec in requirements and also to support creating a test suite. Dave said he understands and asked me to close this issue.
